name: orion_bot
description: Orion Bot — MetaSearch deluxe (DuckDuckGo, Wikipedia, Bing, Reddit, StackOverflow)
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3
  google_fonts: ^6.3.1
  http: ^1.5.0
  characters: ^1.4.0
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  permission_handler_apple: ^9.4.7
  permission_handler_platform_interface: ^4.3.0
  permission_handler_windows: ^0.2.1
  speech_to_text: ^7.3.0
  animated_text_kit: ^4.2.2
  math_expressions: ^2.5.0
  html: ^0.15.0
  # removed material_color_utilities

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
